### ISSUE TITLE
Can't work with ViaFabric 0.4.10+40-main (version:1.20.1)

### ISSUE THREAD

**Issue by lonelysam3** [astei/krypton#103]
Logs:
[14:45:41] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[14:45:43] [main/WARN]: Mod resolution failed
[14:45:43] [main/INFO]: Immediate reason: [NEG_HARD_DEP viafabric 0.4.10+40-main {breaks krypton @ [*]}, ROOT_FORCELOAD_SINGLE krypton 0.2.3, ROOT_FORCELOAD_SINGLE viafabric 0.4.10+40-main]
[14:45:43] [main/INFO]: Reason: [NEG_HARD_DEP viafabric 0.4.10+40-main {breaks krypton @ [*]}, HARD_DEP viafabric-mc114 0.4.10+40-main {depends minecraft @ [1.14.4]}, HARD_DEP viafabric-mc115 0.4.10+40-main {depends minecraft @ [1.15.2]}, HARD_DEP viafabric-mc116 0.4.10+40-main {depends minecraft @ [1.16.5]}, HARD_DEP viafabric-mc117 0.4.10+40-main {depends minecraft @ [1.17.1]}, HARD_DEP viafabric-mc118 0.4.10+40-main {depends minecraft @ [1.18.2]}, HARD_DEP viafabric-mc119 0.4.10+40-main {depends minecraft @ [1.19.4]}]
[14:45:43] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, cotton-client-commands, fabric-models-v0, fabric-client-tags-api-v1, fabric-sound-api-v1, fabric-screen-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[14:45:43] [main/INFO]: Fix: add [], remove [], replace [[viafabric 0.4.10+40-main] -> add:viafabric 1 ([(-∞,∞)])]
[14:45:44] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'ViaFabric' (viafabric) 0.4.10+40-main with any version that is compatible with:
		 - krypton 0.2.3
Unmet dependency listing:
	 - Mod 'ViaFabric' (viafabric) 0.4.10+40-main is incompatible with any version of mod 'Krypton' (krypton), but a matching version is present: 0.2.3!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.10+40-main requires version 1.14.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.10+40-main requires version 1.15.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.10+40-main requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.10+40-main requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.10+40-main requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.19' (viafabric-mc119) 0.4.10+40-main requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2.jar:0.11.2]

**Comment by lonelysam3** [comment]
please fix it! i can use krypton with viafabric 1.19.3!

**Comment by astei** [comment]
Update ViaFabric. It was updated to support Krypton last week.

**Comment by lonelysam3** [comment]
![image](https://github.com/astei/krypton/assets/109451881/1bb92c53-a6d3-4dcf-b506-a7670e1bf36a)
it seems that 0.4.10+40-main is the latest version :(

**Comment by lonelysam3** [comment]
@astei it seems that i had already updated viaversion to the latest version(0.4.10+40-main) :(

**Comment by astei** [comment]
Okay, well, then it's a ViaFabric problem, it's not my problem. The special ViaFabric hack had to go. It's not like it was a big mystery.

**Comment by lonelysam3** [comment]
ok,thank you
