### ISSUE TITLE
Scoreboard Team Packet Error

### ISSUE THREAD

**Issue by LilyKensa** [astei/krypton#120]
## The issue

I used Minecraft 1.21 with Krypton to connect to my own server (Paper 1.21-124-master@df3b654 <- Velocity 3.3.0-SNAPSHOT)
And one of my sub-server is a dungeons minigame, but that involves changing scoreboard teams when starting the game, and I got kicked for some reason.

## Crash Report

<details>
  <summary>It's too long so I put a spoiler here</summary>
  
  ```
---- Minecraft Network Protocol Error Report ----
// Anyone cares if I changed this text here?

Time: 2024-08-03 17:55:11
Description: Packet handling error

java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'waiting'.
	at net.minecraft.class_269.method_1157(class_269.java:308)
	at net.minecraft.class_634.method_11099(class_634.java:2050)
	at net.minecraft.class_5900.method_34173(class_5900.java:132)
	at net.minecraft.class_5900.method_11054(class_5900.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_269.method_1157(class_269.java:308)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:set_player_team
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at net.minecraft.class_2600.method_59803(class_2600.java:56)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_59807(class_8673.java:113)
	at net.minecraft.class_2600.method_11072(class_2600.java:32)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: Paper (Velocity)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 30822240 bytes (29 MiB) / 7868514304 bytes (7504 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6070
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 30.0.101.1371
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 35622.10
	Virtual memory used (MiB): 30418.26
	Swap memory total (MiB): 19573.81
	Swap memory used (MiB): 2290.79
	Space in storage for jna.tmpdir (MiB): available: 133694.69, total: 487008.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 133694.69, total: 487008.31
	Space in storage for io.netty.native.workdir (MiB): available: 133694.69, total: 487008.31
	Space in storage for java.io.tmpdir (MiB): available: 133694.69, total: 487008.31
	Space in storage for workdir (MiB): available: 133694.69, total: 487008.31
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 21.0.0
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		armortrimitemfix: Armor Trim Item Fix 1.1.0
		autoclicker-fabric: Auto Clicker 21.0.2
		autoswitch: AutoSwitch 9.1.1
			autoswitch-api: AutoSwitch API 3.0.0
		badoptimizations: BadOptimizations 2.1.4
		bettercommandblockui: BetterCommandBlockUI 0.5.2
		betterf3: BetterF3 11.0.1
		betterthirdperson: Better Third Person 1.9.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.107+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.107+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.107+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.107+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.107+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.107+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.107+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.107+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.107+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.107+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.107+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.107+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.107+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.107+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.107+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.107+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.107+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.107+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.107+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.107+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.107+1.21
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		catalogue: Catalogue 1.10.1
		chat_heads: Chat Heads 0.12.9
		chatanimation: ChatAnimation 1.0.6
		chatnotify: ChatNotify 2.1.0-beta.2
		chatpatches: Chat Patches 210.6.5.1
		chatsigninghider: Chat Signing Hider 1.21-1.0.5
		chunksfadein: Chunks Fade In 1.0.1-1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.0.0
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		custom-crosshair-mod: Custom Crosshair Mod 1.6.0-fabric
		disablerocketplaced: Disable rocket Placed 1.0.0
		distanthorizons: Distant Horizons 2.1.2-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		eatinganimationid: Eating Animation 1.21+1.9.72
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.100.8+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.13+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.26+a5d66753d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.83+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fabrishot: Fabrishot 1.14.0
		fallingleaves: Falling Leaves 1.16.2
		fancymenu: FancyMenu 3.2.5
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		ferritecore: FerriteCore 7.0.0
		forgeconfigapiport: Forge Config API Port 21.0.7
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		freecam: Freecam 1.3.0-beta1+mc1.21
		geophilic: Geophilic 3.1.1
		held-item-info: Held Item Info 1.7.0
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.2.0
		indium: Indium 1.0.34+mc1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.3
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 15.1.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		jjelytraswap: Auto Elytra Swap 2.1
		konkrete: Konkrete 1.9.9
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		libipn: libIPN 6.0.2
		lithium: Lithium 0.12.7
		melody: Melody 1.0.10
		menulogue: Menulogue 1.21-1.0.6
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.0+mc1.21
		mousetweaks: Mouse Tweaks 2.26
		mr_witherswrath: Wither's Wrath 1.7.1
		notenoughanimations: NotEnoughAnimations 1.7.4
		nvidium: Nvidium 0.2.9-beta
		obsidianui: ObsidianUI 0.2.7+mc1.21
		optigui: OptiGUI 2.3.0-beta.2+1.21
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		panorama: Panorama 1.3.0
		physicsmod: Physics Mod 3.0.16
		pickupnotifier: Pick Up Notifier 21.0.0
		placeholder-api: Placeholder API 2.4.1+1.21
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		puzzleslib: Puzzles Lib 21.0.18
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		reputation: Your Reputation 0.2.7+jade.1.21
		ryoamiclights: RyoamicLights 0.2.9+mc1.21
		shulkerboxtooltip: Shulker Box Tooltip 5.0.4+1.21
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.5
		tia: Tiny Item Animations 1.2
		viafabricplus: ViaFabricPlus 3.4.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.0.2-20240717.170712-16
			com_viaversion_viaversion-common: viaversion-common 5.0.2-20240719.093012-26
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.6
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.6
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.6
			io_netty_netty-codec-http: netty-codec-http 4.1.111
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.5.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_lenni0451_reflect: Reflect 1.3.2
			net_raphimc_minecraftauth: MinecraftAuth 4.0.3-SNAPSHOT
			net_raphimc_viaaprilfools: ViaAprilFools 3.0.1-20240719.220217-9
			net_raphimc_viabedrock: ViaBedrock 0.0.10-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 3.0.2-20240714.181616-4
			net_raphimc_vialoader: ViaLoader 3.0.2-20240716.014912-6
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		visiblebarriers: Visible Barriers 2.0.15
		vmp: Very Many Players 0.2.0+beta.7.163+1.21
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: ComplementaryUnbound_r5.2.1.zip
		Profile: Custom (+34 options changed by user)
  ```
</details>

**Comment by LilyKensa** [comment]
wait a min

**Comment by astei** [comment]
doesn't seem related to Krypton - probably a plugin on your server doing something it shouldn't be doing.

**Comment by LilyKensa** [comment]
i was going to say that
the issue is back even if the mod is removed
i'm dumb
sorry for wasting ur time
gotta go check something else

**Comment by LilyKensa** [comment]
I'm back here in case somebody searched google and find this post.

The problem is that one of my velocity plugin, `velocitab`, is using scoreboard team in order to sort players on the tab-list.
If the backend server have to use scoreboard teams, you need to disable the `send_scoreboard_packets` option in the `velocitab` config

I apologize again for opening an issue without fully understanding the situation.
