### ISSUE TITLE
Kicks half of players randomly during reload

### ISSUE THREAD

**Issue by Neubulae** [astei/krypton#47]
I grabbed latest build on jenkins. No error shown on either side, client nor server

**Comment by Neubulae** [comment]
This problem is only reproducable when a few player joins the server. I have gathered a few friends with Krypton removed and the problem is seemingly irreproducable after removing Krypton. [Here](https://github.com/ViaVersion/ViaFabric/issues/153)'s an issue I've (wrongly) opened on Via's repo

**Comment by astei** [comment]
Without more information like log messages or specific errors I am unable to investigate the issue.

**Comment by Neubulae** [comment]
> Without more information like log messages, a mod list, or specific errors I am unable to investigate the issue.

I had them in the issue I've linked. I'll post them here then. No error messeges are produced on either side tho

**Comment by Neubulae** [comment]
modlist
```

**Comment by Neubulae** [comment]
with ViaVersion I've captured one error message on the console, too bad the message only showed up one during the entirety of my tests conducted and the log is deleted too. The only thing remaining is this picture.
https://user-images.githubusercontent.com/24774842/129962197-cb01556d-da96-49c4-a6bc-a59156cf3d3b.png

**Comment by Neubulae** [comment]
after installing `Why did my Netty fail` on my client I found these outputting in my client log while disconnecting:
```
[16:24:58] [Netty Epoll Client IO #3/FATAL]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: malformed input around byte 5
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.14) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: malformed input around byte 5
	at net.minecraft.network.PacketByteBuf.readNbt(PacketByteBuf:452) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readNbt(PacketByteBuf:432) ~[?:?]
	at de.siphalor.nbtcrafting.ingredient.IngredientEntryCondition.read(IngredientEntryCondition.java:96) ~[nbtcrafting-2.0.18+mc1.17.jar:?]
	at de.siphalor.nbtcrafting.ingredient.IngredientMultiStackEntry.read(IngredientMultiStackEntry.java:93) ~[nbtcrafting-2.0.18+mc1.17.jar:?]
	at net.minecraft.recipe.Ingredient.handler$zmo000$fromPacket(Ingredient:688) ~[?:?]
	at net.minecraft.recipe.Ingredient.fromPacket(Ingredient) ~[?:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe:285) ~[?:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe:260) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.readRecipe(SynchronizeRecipesS2CPacket:45) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readCollection(PacketByteBuf:123) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readList(PacketByteBuf:136) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.<init>(SynchronizeRecipesS2CPacket:22) ~[?:?]
	at net.minecraft.network.NetworkState$PacketHandler.createPacket(NetworkState:411) ~[?:?]
	at net.minecraft.network.NetworkState.getPacketHandler(NetworkState:452) ~[?:?]
	at net.minecraft.network.DecoderHandler.decode(DecoderHandler:34) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 33 more
Caused by: java.io.UTFDataFormatException: malformed input around byte 5
	at java.io.DataInputStream.readUTF(DataInputStream.java:662) ~[?:?]
	at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:287) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.nbt.NbtIo.read(NbtIo:105) ~[?:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo:75) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readNbt(PacketByteBuf:450) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readNbt(PacketByteBuf:432) ~[?:?]
	at de.siphalor.nbtcrafting.ingredient.IngredientEntryCondition.read(IngredientEntryCondition.java:96) ~[nbtcrafting-2.0.18+mc1.17.jar:?]
	at de.siphalor.nbtcrafting.ingredient.IngredientMultiStackEntry.read(IngredientMultiStackEntry.java:93) ~[nbtcrafting-2.0.18+mc1.17.jar:?]
	at net.minecraft.recipe.Ingredient.handler$zmo000$fromPacket(Ingredient:688) ~[?:?]
	at net.minecraft.recipe.Ingredient.fromPacket(Ingredient) ~[?:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe:285) ~[?:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe:260) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.readRecipe(SynchronizeRecipesS2CPacket:45) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readCollection(PacketByteBuf:123) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readList(PacketByteBuf:136) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.<init>(SynchronizeRecipesS2CPacket:22) ~[?:?]
	at net.minecraft.network.NetworkState$PacketHandler.createPacket(NetworkState:411) ~[?:?]
	at net.minecraft.network.NetworkState.getPacketHandler(NetworkState:452) ~[?:?]
	at net.minecraft.network.DecoderHandler.decode(DecoderHandler:34) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 33 more
```
full log attached as following
[latest.log](https://github.com/astei/krypton/files/7082365/latest.log)

**Comment by astei** [comment]
Please narrow down the combination of mods that are causing this error. Does it happen only with Krypton or only in combination with some other mods?

**Comment by Neubulae** [comment]
after some testing I managed to narrow down to NBTCrafting being the real culprit. It's quite hard to reproduce so I'm sorry if I disrupted the issue page..
