### ISSUE TITLE
negative threshold causes NoSuchElementException

### ISSUE THREAD

**Issue by creeper123123321** [astei/krypton#62]
Krypton doesn't follow vanilla behavior of allowing negative values even if compression level is disabled, breaking some servers which use it like [ViaProxy or VIAaaS](https://github.com/RaphiMC/OpenAuthMod#projects-where-this-mod-can-be-used)

```java
java.util.NoSuchElementException: decompress
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.1) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at net.minecraft.network.ClientConnection.handler$zkj000$setCompressionThreshold(ClientConnection:1541) ~[?:?]
	at net.minecraft.network.ClientConnection.setCompressionThreshold(ClientConnection) ~[?:?]
	at
```

**Comment by creeper123123321** [comment]
https://github.com/astei/krypton/commit/80720b286b66b3b0506b8454d2c3264f7bdbea09 fixed
